_core:
  default_config_hash: ijfbzDTN4CbE7Sr-6ubWzy_t1vH4OtU1doNCLssVz-4
langcode: en
name: 'Automated Testing Kit Demonstration '
mail: admin@example.com
slogan: ''
page:
  403: /node/2
  404: /node/1
  front: /node
